"""
Shared data models for the ZainGuard AI investigation pipeline.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


class Severity(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFORMATIONAL = "informational"
    INCONCLUSIVE = "inconclusive"


class Verdict(str, Enum):
    MALICIOUS = "malicious"
    BENIGN = "benign"
    INCONCLUSIVE = "inconclusive"


@dataclass
class Alert:
    """
    A raw security alert or event payload received by the pipeline.

    This is the primary input. It can represent a single alert or be
    part of a batch. The `raw` field holds the original payload as-is
    from the source system (SIEM, EDR, cloud provider, etc.).
    """

    id: str
    title: str
    source: str  # e.g. "wiz", "crowdstrike", "cloudtrail"
    severity: Severity
    raw: dict[str, Any]  # original event payload
    timestamp: datetime = field(default_factory=datetime.utcnow)
    description: str = ""


@dataclass
class InvestigativeQuestion:
    """
    One of the three questions generated by the Director Agent.
    The Investigator Agent is responsible for answering each one.
    """

    number: int  # 1, 2, or 3
    question: str
    rationale: str  # why this question matters for the investigation
    target_layers: list[str] = field(default_factory=list)  # e.g. ["layer1", "layer3"]


@dataclass
class DirectorOutput:
    """Output from the Director Agent."""

    alert_id: str
    triage_summary: str
    key_actors: list[str]  # users, IPs, hostnames involved
    key_assets: list[str]  # EC2 instances, S3 buckets, etc.
    iocs: list[str]  # IPs, domains, hashes to enrich
    questions: list[InvestigativeQuestion]
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class QueryResult:
    """
    Result of a single query executed by the Investigator Agent.
    Absence of data is recorded explicitly — not silently ignored.
    """

    connector: str  # e.g. "snowflake", "virustotal", "glean"
    layer: str  # "layer1", "layer2", or "layer3"
    query: str  # the query or request that was executed
    data: list[dict[str, Any]]  # results (empty list = no results found)
    found: bool  # True if data was returned, False if no results
    error: str | None = None  # set if the query itself failed


@dataclass
class EvidenceItem:
    """
    A single piece of evidence (or notable absence) for one investigative question.
    """

    question_number: int
    question: str
    query_results: list[QueryResult]
    analyst_notes: str  # Investigator's interpretation of the query results
    supports_malicious: bool | None = None  # None = inconclusive


@dataclass
class InvestigatorOutput:
    """Output from the Investigator Agent."""

    alert_id: str
    evidence: list[EvidenceItem]
    raw_ioc_enrichments: list[QueryResult]
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class CaseReport:
    """
    The final output of the investigation pipeline, produced by the Reviewer Agent.
    This is what gets handed to the human analyst.
    """

    alert_id: str
    title: str
    severity: Severity
    verdict: Verdict
    confidence: str  # "high", "medium", "low"

    # Human-readable summaries
    executive_summary: str  # 2-3 sentence summary for non-technical stakeholders
    findings_summary: str  # Detailed findings with evidence references

    # Supporting data
    director_output: DirectorOutput
    investigator_output: InvestigatorOutput

    # Reviewer's assessment
    evidence_gaps: list[str]  # questions not fully answered
    recommendations: list[str]  # short, actionable next steps for the analyst

    # Human review tracking
    requires_human_review: bool = True
    human_reviewed: bool = False
    human_reviewer: str | None = None
    human_notes: str | None = None

    timestamp: datetime = field(default_factory=datetime.utcnow)
